/**
 * Unified API response envelope.
 */
export interface ApiResponse<T> {
  /** Business status code. Success is always 0. */
  code: number;

  /** Human-readable response message. */
  message: string;

  /** Business payload. Error responses return null. */
  data: T | null;

  /** ISO timestamp generated by the backend. */
  timestamp: string;

  /** Request path for debugging and log correlation. */
  path: string;
}

/**
 * Unified API error response envelope.
 */
export interface ApiErrorResponse extends ApiResponse<null> {
  /** Validation or business error details. */
  errors?: unknown;
}
