export interface UploadSignature {
  /** OSS browser direct upload URL. */
  host: string;

  /** Object key generated by backend. The signature only allows uploading to this key. */
  key: string;

  /** Base64 encoded OSS POST Policy. */
  policy: string;

  /** HMAC-SHA1 signature for the encoded policy. */
  signature: string;

  /** RAM access key ID used by the frontend form field OSSAccessKeyId. */
  accessId: string;

  /** ISO expiration time of this upload signature. */
  expireAt: string;

  /** Maximum allowed upload size in bytes. */
  maxFileSize: number;

  /** Expected OSS success status for browser direct upload. */
  successActionStatus: string;
}
